/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author InaRu
 */
public class EmpresaV extends javax.swing.JFrame {

    /**
     * Creates new form EmpresaV
     */
    public EmpresaV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_listadoEmpresa = new javax.swing.JPanel();
        desc_jtxt = new javax.swing.JTextField();
        nomEmpresalbl1 = new javax.swing.JLabel();
        nom_empres_txt = new javax.swing.JTextField();
        nomEmpresalbl = new javax.swing.JLabel();
        limpiarbtn = new javax.swing.JButton();
        agregarEmpresabtn3 = new javax.swing.JButton();
        jP_datosEmpresa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpresas = new javax.swing.JTable();
        modEmpresabtn = new javax.swing.JButton();
        eliminarEmpresabtn = new javax.swing.JButton();
        jMenuBarEmpresa = new javax.swing.JMenuBar();
        jMenuEmpresas = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuProyectos = new javax.swing.JMenu();
        jMenuTareas = new javax.swing.JMenu();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenu();
        jMenuPropuestas = new javax.swing.JMenu();
        jMenuFacturacion = new javax.swing.JMenu();
        jMenuInformes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jP_listadoEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255)), "Datos empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        jP_listadoEmpresa.setForeground(new java.awt.Color(0, 153, 255));

        desc_jtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nomEmpresalbl1.setForeground(new java.awt.Color(0, 153, 255));
        nomEmpresalbl1.setText("Descripción :");

        nom_empres_txt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nom_empres_txt.setOpaque(true);

        nomEmpresalbl.setForeground(new java.awt.Color(0, 153, 255));
        nomEmpresalbl.setText("Nombre empresa:");

        limpiarbtn.setBackground(new java.awt.Color(0, 153, 255));
        limpiarbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpiarbtn.setForeground(new java.awt.Color(255, 255, 255));
        limpiarbtn.setText("Limpiar");
        limpiarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbtnActionPerformed(evt);
            }
        });

        agregarEmpresabtn3.setBackground(new java.awt.Color(0, 153, 255));
        agregarEmpresabtn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregarEmpresabtn3.setForeground(new java.awt.Color(255, 255, 255));
        agregarEmpresabtn3.setText("Agregar");
        agregarEmpresabtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEmpresabtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_listadoEmpresaLayout = new javax.swing.GroupLayout(jP_listadoEmpresa);
        jP_listadoEmpresa.setLayout(jP_listadoEmpresaLayout);
        jP_listadoEmpresaLayout.setHorizontalGroup(
            jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomEmpresalbl)
                    .addComponent(nomEmpresalbl1))
                .addGap(30, 30, 30)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom_empres_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limpiarbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarEmpresabtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jP_listadoEmpresaLayout.setVerticalGroup(
            jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_empres_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomEmpresalbl)
                    .addComponent(agregarEmpresabtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomEmpresalbl1)
                    .addComponent(desc_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jP_datosEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Listado empresas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jTableEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Empresa", "Nombre", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEmpresas);

        javax.swing.GroupLayout jP_datosEmpresaLayout = new javax.swing.GroupLayout(jP_datosEmpresa);
        jP_datosEmpresa.setLayout(jP_datosEmpresaLayout);
        jP_datosEmpresaLayout.setHorizontalGroup(
            jP_datosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_datosEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jP_datosEmpresaLayout.setVerticalGroup(
            jP_datosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_datosEmpresaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        modEmpresabtn.setBackground(new java.awt.Color(0, 153, 255));
        modEmpresabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modEmpresabtn.setForeground(new java.awt.Color(255, 255, 255));
        modEmpresabtn.setText("Modificar");
        modEmpresabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modEmpresabtnActionPerformed(evt);
            }
        });

        eliminarEmpresabtn.setBackground(new java.awt.Color(0, 153, 255));
        eliminarEmpresabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarEmpresabtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarEmpresabtn.setText("Eliminar");
        eliminarEmpresabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmpresabtnActionPerformed(evt);
            }
        });

        jMenuBarEmpresa.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBarEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBarEmpresa.setAutoscrolls(true);
        jMenuBarEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBarEmpresa.setOpaque(true);

        jMenuEmpresas.setText("Empresas");

        jMenuItem2.setText("Modificar empresa");
        jMenuEmpresas.add(jMenuItem2);

        jMenuBarEmpresa.add(jMenuEmpresas);

        jMenuProyectos.setBackground(new java.awt.Color(0, 153, 255));
        jMenuProyectos.setText("Proyectos");
        jMenuBarEmpresa.add(jMenuProyectos);

        jMenuTareas.setText("Tareas");
        jMenuBarEmpresa.add(jMenuTareas);

        jMenuUsuarios.setText("Usuarios");
        jMenuBarEmpresa.add(jMenuUsuarios);

        jMenuClientes.setText("Clientes");
        jMenuBarEmpresa.add(jMenuClientes);

        jMenuPropuestas.setText("Propuestas");
        jMenuBarEmpresa.add(jMenuPropuestas);

        jMenuFacturacion.setText("Facturación");
        jMenuBarEmpresa.add(jMenuFacturacion);

        jMenuInformes.setText("Informes");
        jMenuBarEmpresa.add(jMenuInformes);

        setJMenuBar(jMenuBarEmpresa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_listadoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eliminarEmpresabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modEmpresabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jP_datosEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_listadoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(modEmpresabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarEmpresabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(148, Short.MAX_VALUE)
                    .addComponent(jP_datosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarbtnActionPerformed

    private void modEmpresabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modEmpresabtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modEmpresabtnActionPerformed

    private void eliminarEmpresabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpresabtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarEmpresabtnActionPerformed

    private void agregarEmpresabtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpresabtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarEmpresabtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpresaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpresaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpresaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpresaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpresaV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEmpresabtn3;
    private javax.swing.JTextField desc_jtxt;
    private javax.swing.JButton eliminarEmpresabtn;
    private javax.swing.JMenuBar jMenuBarEmpresa;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuEmpresas;
    private javax.swing.JMenu jMenuFacturacion;
    private javax.swing.JMenu jMenuInformes;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuPropuestas;
    private javax.swing.JMenu jMenuProyectos;
    private javax.swing.JMenu jMenuTareas;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JPanel jP_datosEmpresa;
    private javax.swing.JPanel jP_listadoEmpresa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpresas;
    private javax.swing.JButton limpiarbtn;
    private javax.swing.JButton modEmpresabtn;
    private javax.swing.JLabel nomEmpresalbl;
    private javax.swing.JLabel nomEmpresalbl1;
    private javax.swing.JTextField nom_empres_txt;
    // End of variables declaration//GEN-END:variables
}
