/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author InaRu
 */
public class EmpresasView extends javax.swing.JPanel {

    /**
     * Creates new form Empresas
     */
    public EmpresasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_listadoEmpresa = new javax.swing.JPanel();
        desc_jtxt = new javax.swing.JTextField();
        nomEmpresalbl1 = new javax.swing.JLabel();
        nom_empres_txt = new javax.swing.JTextField();
        nomEmpresalbl = new javax.swing.JLabel();
        limpiarbtn = new javax.swing.JButton();
        agregarEmpresabtn3 = new javax.swing.JButton();
        jP_datosEmpresa1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpresas1 = new javax.swing.JTable();
        eliminarEmpresabtn = new javax.swing.JButton();
        modEmpresabtn = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.controlHighlight);
        setMaximumSize(new java.awt.Dimension(750, 550));
        setMinimumSize(new java.awt.Dimension(750, 550));
        setPreferredSize(new java.awt.Dimension(750, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jP_listadoEmpresa.setBackground(java.awt.SystemColor.controlHighlight);
        jP_listadoEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255)), "Datos empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        jP_listadoEmpresa.setForeground(new java.awt.Color(0, 153, 255));

        desc_jtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nomEmpresalbl1.setForeground(new java.awt.Color(0, 153, 255));
        nomEmpresalbl1.setText("Descripción :");

        nom_empres_txt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nom_empres_txt.setOpaque(true);

        nomEmpresalbl.setForeground(new java.awt.Color(0, 153, 255));
        nomEmpresalbl.setText("Nombre empresa:");

        limpiarbtn.setBackground(new java.awt.Color(0, 153, 255));
        limpiarbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpiarbtn.setForeground(new java.awt.Color(255, 255, 255));
        limpiarbtn.setText("Limpiar");
        limpiarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbtnActionPerformed(evt);
            }
        });

        agregarEmpresabtn3.setBackground(new java.awt.Color(0, 153, 255));
        agregarEmpresabtn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregarEmpresabtn3.setForeground(new java.awt.Color(255, 255, 255));
        agregarEmpresabtn3.setText("Agregar");
        agregarEmpresabtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEmpresabtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_listadoEmpresaLayout = new javax.swing.GroupLayout(jP_listadoEmpresa);
        jP_listadoEmpresa.setLayout(jP_listadoEmpresaLayout);
        jP_listadoEmpresaLayout.setHorizontalGroup(
            jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomEmpresalbl)
                    .addComponent(nomEmpresalbl1))
                .addGap(18, 18, 18)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nom_empres_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(desc_jtxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarEmpresabtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jP_listadoEmpresaLayout.setVerticalGroup(
            jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(nomEmpresalbl))
                    .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nom_empres_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarEmpresabtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomEmpresalbl1)
                        .addComponent(limpiarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(desc_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(jP_listadoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 720, 140));

        jP_datosEmpresa1.setBackground(java.awt.SystemColor.controlHighlight);
        jP_datosEmpresa1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Listado empresas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jTableEmpresas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Empresa", "Nombre", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableEmpresas1);

        eliminarEmpresabtn.setBackground(new java.awt.Color(0, 153, 255));
        eliminarEmpresabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarEmpresabtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarEmpresabtn.setText("Eliminar");
        eliminarEmpresabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmpresabtnActionPerformed(evt);
            }
        });

        modEmpresabtn.setBackground(new java.awt.Color(0, 153, 255));
        modEmpresabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modEmpresabtn.setForeground(new java.awt.Color(255, 255, 255));
        modEmpresabtn.setText("Modificar");
        modEmpresabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modEmpresabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_datosEmpresa1Layout = new javax.swing.GroupLayout(jP_datosEmpresa1);
        jP_datosEmpresa1.setLayout(jP_datosEmpresa1Layout);
        jP_datosEmpresa1Layout.setHorizontalGroup(
            jP_datosEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_datosEmpresa1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jP_datosEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modEmpresabtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarEmpresabtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jP_datosEmpresa1Layout.setVerticalGroup(
            jP_datosEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_datosEmpresa1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jP_datosEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jP_datosEmpresa1Layout.createSequentialGroup()
                        .addComponent(modEmpresabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarEmpresabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(jP_datosEmpresa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 154, 720, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarbtnActionPerformed

    private void agregarEmpresabtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpresabtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarEmpresabtn3ActionPerformed

    private void eliminarEmpresabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpresabtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarEmpresabtnActionPerformed

    private void modEmpresabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modEmpresabtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modEmpresabtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEmpresabtn3;
    private javax.swing.JButton buscarEmpresabtn;
    private javax.swing.JTextField desc_jtxt;
    private javax.swing.JButton eliminarEmpresabtn;
    private javax.swing.JPanel jP_datosEmpresa;
    private javax.swing.JPanel jP_datosEmpresa1;
    private javax.swing.JPanel jP_listadoEmpresa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEmpresas;
    private javax.swing.JTable jTableEmpresas1;
    private javax.swing.JTextField jTxt_buscarEmpresa;
    private javax.swing.JButton limpiarbtn;
    private javax.swing.JButton modEmpresabtn;
    private javax.swing.JLabel nomEmpresalbl;
    private javax.swing.JLabel nomEmpresalbl1;
    private javax.swing.JTextField nom_empres_txt;
    // End of variables declaration//GEN-END:variables
}
