/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author InaRu
 */
public class EmpresasView extends javax.swing.JPanel {

    /**
     * Creates new form Empresas
     */
    public EmpresasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_listadoEmpresa = new javax.swing.JPanel();
        desc_jtxt = new javax.swing.JTextField();
        nomEmpresalbl1 = new javax.swing.JLabel();
        nom_empres_txt = new javax.swing.JTextField();
        nomEmpresalbl = new javax.swing.JLabel();
        limpiarbtn = new javax.swing.JButton();
        agregarEmpresabtn3 = new javax.swing.JButton();
        jP_datosEmpresa = new javax.swing.JPanel();
        jTxt_buscarEmpresa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpresas = new javax.swing.JTable();
        buscarEmpresabtn = new javax.swing.JButton();
        eliminarEmprbtn = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jP_listadoEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255)), "Datos empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        jP_listadoEmpresa.setForeground(new java.awt.Color(0, 153, 255));

        desc_jtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nomEmpresalbl1.setForeground(new java.awt.Color(0, 153, 255));
        nomEmpresalbl1.setText("Descripción :");

        nom_empres_txt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nom_empres_txt.setOpaque(true);

        nomEmpresalbl.setForeground(new java.awt.Color(0, 153, 255));
        nomEmpresalbl.setText("Nombre empresa:");

        limpiarbtn.setBackground(new java.awt.Color(0, 153, 255));
        limpiarbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpiarbtn.setForeground(new java.awt.Color(255, 255, 255));
        limpiarbtn.setText("Editar");
        limpiarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbtnActionPerformed(evt);
            }
        });

        agregarEmpresabtn3.setBackground(new java.awt.Color(0, 153, 255));
        agregarEmpresabtn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregarEmpresabtn3.setForeground(new java.awt.Color(255, 255, 255));
        agregarEmpresabtn3.setText("Agregar");
        agregarEmpresabtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEmpresabtn3ActionPerformed(evt);
            }
        });

        jP_datosEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Listado empresas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jTxt_buscarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_buscarEmpresaActionPerformed(evt);
            }
        });

        jTableEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Empresa", "Nombre", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEmpresas);

        buscarEmpresabtn.setBackground(new java.awt.Color(0, 153, 255));
        buscarEmpresabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscarEmpresabtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarEmpresabtn.setText("Buscar");
        buscarEmpresabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEmpresabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_datosEmpresaLayout = new javax.swing.GroupLayout(jP_datosEmpresa);
        jP_datosEmpresa.setLayout(jP_datosEmpresaLayout);
        jP_datosEmpresaLayout.setHorizontalGroup(
            jP_datosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_datosEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_datosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jP_datosEmpresaLayout.createSequentialGroup()
                        .addComponent(jTxt_buscarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarEmpresabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jP_datosEmpresaLayout.setVerticalGroup(
            jP_datosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_datosEmpresaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jP_datosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_buscarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarEmpresabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        eliminarEmprbtn.setBackground(new java.awt.Color(0, 153, 255));
        eliminarEmprbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarEmprbtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarEmprbtn.setText("Eliminar");
        eliminarEmprbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmprbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_listadoEmpresaLayout = new javax.swing.GroupLayout(jP_listadoEmpresa);
        jP_listadoEmpresa.setLayout(jP_listadoEmpresaLayout);
        jP_listadoEmpresaLayout.setHorizontalGroup(
            jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_datosEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_listadoEmpresaLayout.createSequentialGroup()
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarEmprbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomEmpresalbl)
                            .addComponent(nomEmpresalbl1))
                        .addGap(30, 30, 30)
                        .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nom_empres_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desc_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limpiarbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarEmpresabtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        jP_listadoEmpresaLayout.setVerticalGroup(
            jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_empres_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomEmpresalbl)
                    .addComponent(agregarEmpresabtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomEmpresalbl1)
                    .addComponent(desc_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarEmprbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jP_datosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(jP_listadoEmpresa, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarbtnActionPerformed

    private void agregarEmpresabtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpresabtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarEmpresabtn3ActionPerformed

    private void jTxt_buscarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_buscarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_buscarEmpresaActionPerformed

    private void buscarEmpresabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEmpresabtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarEmpresabtnActionPerformed

    private void eliminarEmprbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmprbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarEmprbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEmpresabtn3;
    private javax.swing.JButton buscarEmpresabtn;
    private javax.swing.JTextField desc_jtxt;
    private javax.swing.JButton eliminarEmprbtn;
    private javax.swing.JPanel jP_datosEmpresa;
    private javax.swing.JPanel jP_listadoEmpresa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpresas;
    private javax.swing.JTextField jTxt_buscarEmpresa;
    private javax.swing.JButton limpiarbtn;
    private javax.swing.JLabel nomEmpresalbl;
    private javax.swing.JLabel nomEmpresalbl1;
    private javax.swing.JTextField nom_empres_txt;
    // End of variables declaration//GEN-END:variables
}
