/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author InaRu
 */
public class Home extends javax.swing.JFrame {

    private Container contenedor;
    private JPanel panel;
    
    
    
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        UsuariosView u = new UsuariosView();
        JFrame jf= new JFrame();
        jf.getContentPane().add(u);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        estadoConexion_lbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_Empresas = new javax.swing.JMenu();
        jM_usuarios = new javax.swing.JMenu();
        jM_Proyectos = new javax.swing.JMenu();
        jM_tareas = new javax.swing.JMenu();
        jM_clientes = new javax.swing.JMenu();
        jM_fact = new javax.swing.JMenu();
        jM_informes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        setMinimumSize(new java.awt.Dimension(38, 38));
        setName("frameHome"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        estadoConexion_lbl.setText("Estado Conexion");
        jPanel1.add(estadoConexion_lbl, "card2");

        getContentPane().add(jPanel1, "card2");

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(390, 32768));
        jMenuBar1.setOpaque(true);

        jM_Empresas.setText("Empresas");
        jMenuBar1.add(jM_Empresas);

        jM_usuarios.setText("Usuarios");
        jMenuBar1.add(jM_usuarios);

        jM_Proyectos.setText("Proyectos");
        jMenuBar1.add(jM_Proyectos);

        jM_tareas.setText("Tareas");
        jMenuBar1.add(jM_tareas);

        jM_clientes.setText("Clientes");
        jMenuBar1.add(jM_clientes);

        jM_fact.setText("Facturación");
        jMenuBar1.add(jM_fact);

        jM_informes.setText("Informes ");
        jMenuBar1.add(jM_informes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estadoConexion_lbl;
    private javax.swing.JMenu jM_Empresas;
    private javax.swing.JMenu jM_Proyectos;
    private javax.swing.JMenu jM_clientes;
    private javax.swing.JMenu jM_fact;
    private javax.swing.JMenu jM_informes;
    private javax.swing.JMenu jM_tareas;
    private javax.swing.JMenu jM_usuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
