/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author InaRu
 */
public class Home extends javax.swing.JFrame {

    private Container contenedor;
    private JPanel panel;
    
    
    
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        UsuariosView u = new UsuariosView();
        JFrame jf= new JFrame();
        jf.getContentPane().add(u);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        clientesJBTN = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_Empresas = new javax.swing.JMenu();
        jM_usuarios = new javax.swing.JMenu();
        jM_Proyectos = new javax.swing.JMenu();
        jM_tareas = new javax.swing.JMenu();
        jM_clientes = new javax.swing.JMenu();
        jM_fact = new javax.swing.JMenu();
        jM_informes = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        setMinimumSize(new java.awt.Dimension(38, 38));
        setName("frameHome"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientesJBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin_person_user_man_2839.png"))); // NOI18N
        clientesJBTN.setText("CLIENTES");
        clientesJBTN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        clientesJBTN.setBorderPainted(false);
        clientesJBTN.setContentAreaFilled(false);
        clientesJBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesJBTNActionPerformed(evt);
            }
        });
        jPanel1.add(clientesJBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 240));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 204));
        jTextField1.setText("Bienvenido a la herramienta  ");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 340, 70));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 153, 255));
        jTextField2.setText("MEDICAL PROJECT MANAGEMENT");
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 420, 50));

        getContentPane().add(jPanel1, "card2");

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(390, 32768));

        jM_Empresas.setText("Empresas");
        jM_Empresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_EmpresasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jM_Empresas);

        jM_usuarios.setText("Usuarios");
        jMenuBar1.add(jM_usuarios);

        jM_Proyectos.setText("Proyectos");
        jMenuBar1.add(jM_Proyectos);

        jM_tareas.setText("Tareas");
        jMenuBar1.add(jM_tareas);

        jM_clientes.setText("Clientes");
        jMenuBar1.add(jM_clientes);

        jM_fact.setText("Facturación");
        jMenuBar1.add(jM_fact);

        jM_informes.setText("Informes ");
        jMenuBar1.add(jM_informes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesJBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesJBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesJBTNActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jM_EmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_EmpresasMouseClicked
        EmpresaV em=new EmpresaV();
        em.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jM_EmpresasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientesJBTN;
    private javax.swing.JMenu jM_Empresas;
    private javax.swing.JMenu jM_Proyectos;
    private javax.swing.JMenu jM_clientes;
    private javax.swing.JMenu jM_fact;
    private javax.swing.JMenu jM_informes;
    private javax.swing.JMenu jM_tareas;
    private javax.swing.JMenu jM_usuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
