/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author InaRu
 */
public class ProyectosView extends javax.swing.JPanel {

    /**
     * Creates new form ProyectosView
     */
    public ProyectosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesProy_jpnl = new javax.swing.JPanel();
        nuevoProy_btn = new javax.swing.JButton();
        editProye_btn = new javax.swing.JButton();
        eliminarProy_btn = new javax.swing.JButton();
        guardarProy_btn = new javax.swing.JButton();
        listaProy_jpnl = new javax.swing.JPanel();
        buscarProy_txt = new javax.swing.JTextField();
        buscarProy_btn = new javax.swing.JButton();
        jScrollP_Proy = new javax.swing.JScrollPane();
        proyectos_jTbl = new javax.swing.JTable();

        opcionesProy_jpnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, null, null, null, null, new java.awt.Color(0, 102, 204)));

        nuevoProy_btn.setBackground(new java.awt.Color(0, 153, 255));
        nuevoProy_btn.setForeground(new java.awt.Color(255, 255, 255));
        nuevoProy_btn.setText("Nuevo");
        nuevoProy_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoProy_btnActionPerformed(evt);
            }
        });

        editProye_btn.setBackground(new java.awt.Color(0, 153, 255));
        editProye_btn.setForeground(new java.awt.Color(255, 255, 255));
        editProye_btn.setText("Editar");

        eliminarProy_btn.setBackground(new java.awt.Color(0, 153, 255));
        eliminarProy_btn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarProy_btn.setText("Eliminar");

        guardarProy_btn.setBackground(new java.awt.Color(0, 153, 255));
        guardarProy_btn.setForeground(new java.awt.Color(255, 255, 255));
        guardarProy_btn.setText("Guardar");
        guardarProy_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarProy_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionesProy_jpnlLayout = new javax.swing.GroupLayout(opcionesProy_jpnl);
        opcionesProy_jpnl.setLayout(opcionesProy_jpnlLayout);
        opcionesProy_jpnlLayout.setHorizontalGroup(
            opcionesProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesProy_jpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(opcionesProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eliminarProy_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(editProye_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nuevoProy_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardarProy_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        opcionesProy_jpnlLayout.setVerticalGroup(
            opcionesProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesProy_jpnlLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(nuevoProy_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editProye_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarProy_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardarProy_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        listaProy_jpnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, null, null, null, null, new java.awt.Color(0, 102, 204)));

        buscarProy_btn.setBackground(new java.awt.Color(0, 153, 255));
        buscarProy_btn.setForeground(new java.awt.Color(255, 255, 255));
        buscarProy_btn.setText("Buscar");

        proyectos_jTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Estado", "Nombre", "Tipo", "Cliente", "Fecha inicio", "Fecha entrega", "MW", "Descripción"
            }
        ));
        jScrollP_Proy.setViewportView(proyectos_jTbl);

        javax.swing.GroupLayout listaProy_jpnlLayout = new javax.swing.GroupLayout(listaProy_jpnl);
        listaProy_jpnl.setLayout(listaProy_jpnlLayout);
        listaProy_jpnlLayout.setHorizontalGroup(
            listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                        .addComponent(jScrollP_Proy, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                        .addComponent(buscarProy_txt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarProy_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );
        listaProy_jpnlLayout.setVerticalGroup(
            listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarProy_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarProy_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollP_Proy, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(listaProy_jpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionesProy_jpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcionesProy_jpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listaProy_jpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoProy_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoProy_btnActionPerformed

    }//GEN-LAST:event_nuevoProy_btnActionPerformed

    private void guardarProy_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarProy_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarProy_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarProy_btn;
    private javax.swing.JTextField buscarProy_txt;
    private javax.swing.JButton editProye_btn;
    private javax.swing.JButton eliminarProy_btn;
    private javax.swing.JButton guardarProy_btn;
    private javax.swing.JScrollPane jScrollP_Proy;
    private javax.swing.JPanel listaProy_jpnl;
    private javax.swing.JButton nuevoProy_btn;
    private javax.swing.JPanel opcionesProy_jpnl;
    private javax.swing.JTable proyectos_jTbl;
    // End of variables declaration//GEN-END:variables
}
