/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SMMS_vista;

import SMMS_modelo.Conexion;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author InaRu
 */
public class Login extends javax.swing.JFrame implements ActionListener{
    
      Conexion c= new Conexion();
      Connection con=c.getConexion();

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar_login = new javax.swing.JToolBar();
        tituloLoginlb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        username_txt = new javax.swing.JTextField();
        entrarbtn = new javax.swing.JButton();
        iconouserlbl = new javax.swing.JLabel();
        pass_jpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        setName("loginJF"); // NOI18N

        jToolBar_login.setBackground(new java.awt.Color(51, 153, 255));
        jToolBar_login.setRollover(true);

        tituloLoginlb.setBackground(new java.awt.Color(255, 255, 255));
        tituloLoginlb.setForeground(new java.awt.Color(255, 255, 255));
        tituloLoginlb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloLoginlb.setLabelFor(tituloLoginlb);
        tituloLoginlb.setText("MEDICAL MANAGMENT SYSTEM - LOGIN");
        tituloLoginlb.setMaximumSize(new java.awt.Dimension(408, 35));
        tituloLoginlb.setPreferredSize(new java.awt.Dimension(48, 16));
        jToolBar_login.add(tituloLoginlb);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        username_txt.setForeground(new java.awt.Color(204, 204, 204));
        username_txt.setText("Usuario");
        username_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_txtActionPerformed(evt);
            }
        });

        entrarbtn.setBackground(new java.awt.Color(51, 153, 255));
        entrarbtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        entrarbtn.setForeground(new java.awt.Color(255, 255, 255));
        entrarbtn.setText("ENTRAR");
        entrarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarbtnMouseClicked(evt);
            }
        });
        entrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarbtnActionPerformed(evt);
            }
        });

        iconouserlbl.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        iconouserlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userblu.png"))); // NOI18N

        pass_jpass.setForeground(new java.awt.Color(204, 204, 204));
        pass_jpass.setText("Contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(iconouserlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pass_jpass, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(entrarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(iconouserlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pass_jpass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(entrarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar_login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarbtnActionPerformed
       validarUsuario();
    }//GEN-LAST:event_entrarbtnActionPerformed

    private void username_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_txtActionPerformed

    private void entrarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarbtnMouseClicked
        String usuario="admin";
        String contrasenya="viu";
         
        String user=username_txt.getText();
        String pass = new String(pass_jpass.getPassword());
      
         
         if (user.equals(usuario) && pass.equals(contrasenya))  {
             
             Home h =new Home();
             this.setVisible(false);
             h.setVisible(true);  
             dispose();
            } 
         else
             {
             
             JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrecto");
             
             }   
                               
    }//GEN-LAST:event_entrarbtnMouseClicked

    /**
     * Método que permite validar el usuario
     */
    public void validarUsuario(){
        
        int resultado;
        String pass=String.valueOf(pass_jpass.getPassword());
        String usuario=username_txt.getText();
        String SQL;
        SQL = "SELECT * FROM USUARIOS WHERE nom_usuario='"+usuario+"' and passw='"+pass+"' ";
        
        try{
         Statement st= con.createStatement();
         ResultSet rs=st.executeQuery(SQL);
         
         if (rs.next()){
             resultado=1;
             if(resultado==1){
                 Home h = new Home();
                 h.setVisible(true);
                 this.dispose();
             }
             
         }else{
             
             JOptionPane.showMessageDialog(this, "Acceso denegado! Usuario incorrecto");
         }
            
            
        } catch (HeadlessException | SQLException e) {
            
            JOptionPane.showMessageDialog(null," Error:  " + e.getMessage());
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrarbtn;
    private javax.swing.JLabel iconouserlbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar_login;
    private javax.swing.JPasswordField pass_jpass;
    private javax.swing.JLabel tituloLoginlb;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param e
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
